services:
  timelapse_creator:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./config.py:/app/config.py:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
      - appmode=timelapse